nodes <- list(c("alata", "albolutescens", "bebbii", "bicknellii", "brevior", 
"buffaloriver", "crawfordii", "cristatella", "cumulata", "festucacea", 
"feta", "hormathodes", "hyalina", "longii", "merrittfernaldii", 
"missouriensis", "molesta", "molestiformis", "muskingumensis", 
"normalis", "opaca", "oronensis", "ovalis3098", "ozarkana", "projecta", 
"reniformis", "scopariaVscoparia", "scopariaVtessellata", "shinnersii", 
"straminea", "suberecta", "teneraVechinodes", "teneraVtenera", 
"tincta", "tribuloidesVtribuloides", "vexans", "adusta", "athrostachya", 
"pachystachya", "xerantica", "macloviana"), c("alata", "albolutescens", 
"bebbii", "bicknellii", "brevior", "buffaloriver", "crawfordii", 
"cristatella", "cumulata", "festucacea", "feta", "hormathodes", 
"hyalina", "longii", "merrittfernaldii", "missouriensis", "molesta", 
"molestiformis", "muskingumensis", "normalis", "opaca", "oronensis", 
"ovalis3098", "ozarkana", "projecta", "reniformis", "scopariaVscoparia", 
"scopariaVtessellata", "shinnersii", "straminea", "suberecta", 
"teneraVechinodes", "teneraVtenera", "tincta", "tribuloidesVtribuloides", 
"vexans"), c("bebbii", "bicknellii", "brevior", "buffaloriver", 
"crawfordii", "cristatella", "cumulata", "festucacea", "hyalina", 
"merrittfernaldii", "missouriensis", "molesta", "molestiformis", 
"muskingumensis", "normalis", "opaca", "oronensis", "projecta", 
"reniformis", "shinnersii", "teneraVechinodes", "teneraVtenera", 
"tincta", "tribuloidesVtribuloides", "feta", "ovalis3098"), c("bebbii", 
"bicknellii", "brevior", "buffaloriver", "crawfordii", "cristatella", 
"cumulata", "festucacea", "hyalina", "merrittfernaldii", "missouriensis", 
"molesta", "molestiformis", "muskingumensis", "normalis", "opaca", 
"oronensis", "projecta", "reniformis", "shinnersii", "teneraVechinodes", 
"teneraVtenera", "tincta", "tribuloidesVtribuloides"), c("brevior", 
"hyalina", "molestiformis", "reniformis", "shinnersii"), c("suberecta", 
"albolutescens", "scopariaVscoparia", "scopariaVtessellata", 
"alata", "vexans", "longii"), c("subfusca", "integra", "peucophila", 
"microptera", "haydeniana", "ebenea"), c("phaeocephala", "preslii", 
"argyrantha"))
