taxonSets <- list(ENA = c("alata", "albolutescens", "bebbii", "bicknellii", 
"brevior", "buffaloriver", "crawfordii", "cristatella", "cumulata", 
"festucacea", "feta", "hormathodes", "hyalina", "longii", "merrittfernaldii", 
"missouriensis", "molesta", "molestiformis", "muskingumensis", 
"normalis", "opaca", "oronensis", "ovalis3098", "ozarkana", "projecta", 
"reniformis", "scopariaVscoparia", "scopariaVtessellata", "shinnersii", 
"straminea", "suberecta", "teneraVechinodes", "teneraVtenera", 
"tincta", "tribuloidesVtribuloides", "vexans"), ENAI = c("bebbii", 
"bicknellii", "brevior", "buffaloriver", "crawfordii", "cristatella", 
"cumulata", "festucacea", "hyalina", "merrittfernaldii", "missouriensis", 
"molesta", "molestiformis", "muskingumensis", "normalis", "opaca", 
"oronensis", "projecta", "reniformis", "shinnersii", "teneraVechinodes", 
"teneraVtenera", "tincta", "tribuloidesVtribuloides"), ENAII = c("alata", 
"albolutescens", "hormathodes", "longii", "ozarkana", "scopariaVscoparia", 
"scopariaVtessellata", "straminea", "suberecta", "vexans"), ENAIII = c("feta", 
"ovalis3098"), WNA = c("adusta", "argyrantha", "athrostachya", 
"bohemica", "ebenea", "foenea", "haydeniana", "integra", "macloviana", 
"microptera", "pachystachya", "peucophila", "phaeocephala", "praticola", 
"preslii", "subfusca", "xerantica"), WNAI = c("argyrantha", "bohemica", 
"ebenea", "foenea", "haydeniana", "integra", "microptera", "peucophila", 
"phaeocephala", "praticola", "preslii", "subfusca"), WNAII = c("adusta", 
"athrostachya", "pachystachya", "xerantica", "macloviana"))